#!/bin/bash
set -euo pipefail

fqdn=$1
zone2=$(echo ${fqdn} | sed -e 's/.*\.\(.*\..*\)/\1/')
email=${2:-postmaster@$zone2}

docker run --rm \
  -v /etc/letsencrypt:/etc/letsencrypt \
  -v /var/www/letsencrypt:/var/www/letsencrypt \
  certbot/certbot \
  certonly \
  --non-interactive \
  --preferred-challenges http-01 \
  --agree-tos \
  --webroot -w /var/www/letsencrypt \
  -d $fqdn \
  --rsa-key-size 4096 \
  --hsts \
  --email $email
