#!/bin/bash
set -euo pipefail

fqdn=$1
zone2=$(echo ${fqdn} | sed -e 's/.*\.\(.*\..*\)/\1/')
email=${2:-postmaster@$zone2}

docker-compose run certbot \
  certbot \
  certonly \
  --text \
  --standalone-supported-challenges http-01 \
  --agree-tos \
  --webroot -w /mnt/ -d $fqdn \
  --rsa-key-size 4096 \
  --must-staple \
  --hsts \
  --email $email
