#!/bin/bash
set -euo pipefail

docker run \
  --name nginx-certbot \
  --net=host \
  --detach \
  --restart=unless-stopped \
  -v /etc/letsencrypt:/etc/letsencrypt \
  -v /var/log/letsencrypt:/var/log/letsencrypt \
  -v /var/www/letsencrypt:/var/www/letsencrypt \
  -v ${PWD}/etc/nginx/conf.d:/etc/nginx/conf.d \
  -v ${PWD}/etc/nginx/letsencrypt_well_known.conf:/etc/nginx/letsencrypt_well_known.conf \
  nginx:1.21
